### PR TITLE
OpenFl 3.6.0 and Lime 2.9.0 compilation fixes

### PR DESCRIPTION
**Pull request by mmauri**
-Fixed compilation errors under new versions of OpenFl and Lime
Removed lots of untyped Object, and ObjectMap<Object,Object>
Also removed TweenLite, as I was unable to fix it to compile under 3.6.0, and moved to Actuate
Beware that the performance is worse than the original version, still working on it.

Polygon sample, doesn't compile yet

### CODE REVIEW

**Comment by skaronn** [comment]
Thanks Marc. I will try it soon and let you know.

**Comment by skaronn** [comment]
First of all thanks a lot for this hard work. I've tested your fixes and it's pretty good :+1: 

But I have some comments :

1- The most recent version of modestmaps is modestmap js 3.3.6 with features like cabspotting or spotlight that are not yet included in the haxe version. So I don't think we should change the library directory version to 3.3.7 until we reach to port all those features.

2 - Both samples mapselector and polygons don't compile but I have the fixes.

3 - I don't really like the performance of Actuate maybe we will back to the previous Tweenlite after the merge. I've already worked on it.

So I will ask you perform another pull request with the good library version directory please.

Thanks and regards

Marcus

**Comment by mmauri** [comment]
Hi Marcus,
Thanks for your encouragement, this is my first approach to Haxe and OpenFL as a night hobby.
It feels great to write some code again ;)

I will change to 3.3.6 and will update the repo during the weekend.
I agree that the performance of actuate is worse, but I was unable to fix the compile errors of the Tweenlite class, if you can it would be awesome.

After the merge, I will try fo fix the errors for the html5 output if you agree with that.

Best regards,
Marc

**Comment by skaronn** [comment]
I'll push the fix for html5 compilation very soon...

Thanks and regards

Marcus

**Pull request closed without merging**
